name = "FIRLSFilterDesign"
uuid = "1d969ca1-ee82-491a-b198-7f2f63a25c18"
authors = ["Lenard Koomen <l.koomen92@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Documenter = "0.26, 0.27"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
